version: '3.8'

services:
  native-service:
    build:
      context: ./
      dockerfile: ./Dockerfile-dev
    container_name: native-container
    volumes:
      - ./:/usr/src/app/
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002
      - 19006:19006
    user: ${USER_ID}
    stdin_open: true
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
